name: Publish Docker Image

on:
  release:
    types:
      - created
  push:
    tags:
      - '*'

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - id: get_version
        uses: battila7/get-version-action@v2
      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          build-args: |
            VERSION=${{ steps.get_version.outputs.version-without-v }}
          tags: |
            ghcr.io/wirepact/translators/poc-demo-translator:latest
            ghcr.io/wirepact/translators/poc-demo-translator:${{ steps.get_version.outputs.version-without-v }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
